/* ================================================================
   OSINT GENIUS - Report Generator
   ================================================================ */
window.Report = {
  generateHTML() {
    const cases = Storage.getCases();
    const history = Storage.getHistory();
    const notes = Storage.getNotes();
    const now = new Date().toLocaleString();

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>OSINT GENIUS Report - ${now}</title>
<style>
  * { box-sizing:border-box; margin:0; padding:0; }
  body { font-family:'Segoe UI',Arial,sans-serif; background:#f5f7fa; color:#1a1a2e; }
  .report-header { background:linear-gradient(135deg,#050508,#0f0f1a); color:#fff; padding:40px; }
  .report-header h1 { font-size:2rem; letter-spacing:.1em; color:#00d4ff; }
  .report-header .sub { color:rgba(255,255,255,.5); font-size:.85rem; margin-top:6px; font-family:monospace; }
  .section { padding:30px 40px; border-bottom:1px solid #e0e0e0; }
  .section h2 { font-size:1.1rem; color:#1a1a2e; margin-bottom:16px; padding-bottom:8px; border-bottom:2px solid #00d4ff; display:inline-block; }
  .case-card { background:#fff; border:1px solid #e0e0e0; border-radius:8px; padding:16px; margin-bottom:12px; border-left:4px solid #00d4ff; }
  .case-title { font-weight:700; font-size:.95rem; }
  .case-meta { font-size:.75rem; color:#888; margin-top:4px; }
  .badge { display:inline-block; padding:2px 8px; border-radius:4px; font-size:.7rem; font-weight:700; margin-right:4px; }
  .badge-ip { background:#e3f2fd; color:#1565c0; }
  .badge-domain { background:#e8f5e9; color:#2e7d32; }
  .badge-person { background:#f3e5f5; color:#6a1b9a; }
  .badge-email { background:#fff3e0; color:#e65100; }
  .hist-item { display:flex; gap:16px; padding:8px 0; border-bottom:1px solid #f0f0f0; font-size:.82rem; }
  .hist-module { font-weight:600; color:#00d4ff; min-width:120px; }
  .hist-query { font-family:monospace; color:#333; }
  .hist-time { color:#aaa; margin-left:auto; }
  .notes-block { background:#fffde7; border:1px solid #f9a825; border-radius:8px; padding:16px; white-space:pre-wrap; font-size:.85rem; line-height:1.7; }
  .footer { text-align:center; padding:20px; color:#aaa; font-size:.75rem; }
  .stats-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin-bottom:20px; }
  .stat-box { background:#fff; border:1px solid #e0e0e0; border-radius:8px; padding:16px; text-align:center; }
  .stat-box .val { font-size:1.8rem; font-weight:700; color:#00d4ff; font-family:monospace; }
  .stat-box .lbl { font-size:.7rem; color:#888; text-transform:uppercase; letter-spacing:.06em; margin-top:4px; }
  @media print { body { background:#fff; } }
</style>
</head>
<body>
<div class="report-header">
  <h1>&#9679; OSINT GENIUS</h1>
  <div class="sub">Intelligence Report &nbsp;|&nbsp; Generated: ${now}</div>
</div>

<div class="section">
  <h2>Summary Statistics</h2>
  <div class="stats-grid">
    <div class="stat-box"><div class="val">${cases.length}</div><div class="lbl">Total Cases</div></div>
    <div class="stat-box"><div class="val">${history.length}</div><div class="lbl">Total Searches</div></div>
    <div class="stat-box"><div class="val">16</div><div class="lbl">Modules</div></div>
    <div class="stat-box"><div class="val">${new Date().getFullYear()}</div><div class="lbl">Year</div></div>
  </div>
</div>

<div class="section">
  <h2>Investigation Cases (${cases.length})</h2>
  ${cases.length === 0 ? '<p style="color:#aaa;font-size:.85rem;">No cases recorded.</p>' :
    cases.map(c => `
      <div class="case-card">
        <div class="case-title">${c.name || 'Untitled Case'}</div>
        <div class="case-meta">
          <span class="badge badge-${c.type||'ip'}">${(c.type||'general').toUpperCase()}</span>
          Target: <strong>${c.target || 'N/A'}</strong> &nbsp;|&nbsp;
          Created: ${new Date(c.createdAt).toLocaleString()}
        </div>
        ${c.description ? `<div style="margin-top:8px;font-size:.82rem;color:#555;">${c.description}</div>` : ''}
      </div>
    `).join('')}
</div>

<div class="section">
  <h2>Search History (last ${Math.min(history.length,50)})</h2>
  ${history.slice(0,50).map(h => `
    <div class="hist-item">
      <span class="hist-module">${h.moduleName||h.module}</span>
      <span class="hist-query">${h.query}</span>
      <span class="hist-time">${new Date(h.timestamp).toLocaleString()}</span>
    </div>
  `).join('')}
</div>

${notes ? `
<div class="section">
  <h2>Analyst Notes</h2>
  <div class="notes-block">${notes}</div>
</div>` : ''}

<div class="footer">
  Generated by OSINT GENIUS Intelligence Platform &nbsp;|&nbsp; For authorized use only
</div>
</body>
</html>`;
  },

  openReport() {
    const html = this.generateHTML();
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    setTimeout(() => URL.revokeObjectURL(url), 60000);
  }
};
